// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// nll_cov_cpp
double nll_cov_cpp(const Eigen::VectorXd& E_obs, const Eigen::MatrixXd& V_obs, const Eigen::VectorXd& E_pred, const Eigen::MatrixXd& V_pred, double n);
RcppExport SEXP _admixr2_nll_cov_cpp(SEXP E_obsSEXP, SEXP V_obsSEXP, SEXP E_predSEXP, SEXP V_predSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type E_obs(E_obsSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type V_obs(V_obsSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type E_pred(E_predSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type V_pred(V_predSEXP);
    Rcpp::traits::input_parameter< double >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(nll_cov_cpp(E_obs, V_obs, E_pred, V_pred, n));
    return rcpp_result_gen;
END_RCPP
}
// nll_var_cpp
double nll_var_cpp(const Eigen::VectorXd& E_obs, const Eigen::VectorXd& v_obs, const Eigen::VectorXd& E_pred, const Eigen::VectorXd& v_pred, double n);
RcppExport SEXP _admixr2_nll_var_cpp(SEXP E_obsSEXP, SEXP v_obsSEXP, SEXP E_predSEXP, SEXP v_predSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type E_obs(E_obsSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type v_obs(v_obsSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type E_pred(E_predSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type v_pred(v_predSEXP);
    Rcpp::traits::input_parameter< double >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(nll_var_cpp(E_obs, v_obs, E_pred, v_pred, n));
    return rcpp_result_gen;
END_RCPP
}
// logdmvnorm_batch_cpp
Eigen::VectorXd logdmvnorm_batch_cpp(const Eigen::MatrixXd& bi_mat, const Eigen::VectorXd& mean_vec, const Eigen::MatrixXd& L);
RcppExport SEXP _admixr2_logdmvnorm_batch_cpp(SEXP bi_matSEXP, SEXP mean_vecSEXP, SEXP LSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type bi_mat(bi_matSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type mean_vec(mean_vecSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type L(LSEXP);
    rcpp_result_gen = Rcpp::wrap(logdmvnorm_batch_cpp(bi_mat, mean_vec, L));
    return rcpp_result_gen;
END_RCPP
}
// softmax_cpp
Eigen::VectorXd softmax_cpp(const Eigen::VectorXd& lw);
RcppExport SEXP _admixr2_softmax_cpp(SEXP lwSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type lw(lwSEXP);
    rcpp_result_gen = Rcpp::wrap(softmax_cpp(lw));
    return rcpp_result_gen;
END_RCPP
}
// weighted_meancov_cpp
Rcpp::List weighted_meancov_cpp(const Eigen::MatrixXd& F, const Eigen::VectorXd& w);
RcppExport SEXP _admixr2_weighted_meancov_cpp(SEXP FSEXP, SEXP wSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type F(FSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type w(wSEXP);
    rcpp_result_gen = Rcpp::wrap(weighted_meancov_cpp(F, w));
    return rcpp_result_gen;
END_RCPP
}
// compute_mean_new_cpp
Eigen::VectorXd compute_mean_new_cpp(const Eigen::VectorXd& struct_paired, const Eigen::VectorXd& log_origbeta, const Eigen::VectorXi& transform_type, const Eigen::VectorXd& low, const Eigen::VectorXd& hi);
RcppExport SEXP _admixr2_compute_mean_new_cpp(SEXP struct_pairedSEXP, SEXP log_origbetaSEXP, SEXP transform_typeSEXP, SEXP lowSEXP, SEXP hiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type struct_paired(struct_pairedSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type log_origbeta(log_origbetaSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXi& >::type transform_type(transform_typeSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type low(lowSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type hi(hiSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_mean_new_cpp(struct_paired, log_origbeta, transform_type, low, hi));
    return rcpp_result_gen;
END_RCPP
}
// irmc_inner_nll_cpp
double irmc_inner_nll_cpp(const Eigen::MatrixXd& rawpreds, const Eigen::MatrixXd& bi_mat, const Eigen::VectorXd& mean_new, const Eigen::MatrixXd& L_omega, const Eigen::VectorXd& log_prop, const Eigen::VectorXd& E_obs, const Eigen::MatrixXd& V_obs, double n, const Eigen::VectorXd& sigma_var, const Eigen::VectorXi& sigma_type, const Eigen::VectorXd& kappa_delta, int use_var);
RcppExport SEXP _admixr2_irmc_inner_nll_cpp(SEXP rawpredsSEXP, SEXP bi_matSEXP, SEXP mean_newSEXP, SEXP L_omegaSEXP, SEXP log_propSEXP, SEXP E_obsSEXP, SEXP V_obsSEXP, SEXP nSEXP, SEXP sigma_varSEXP, SEXP sigma_typeSEXP, SEXP kappa_deltaSEXP, SEXP use_varSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type rawpreds(rawpredsSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type bi_mat(bi_matSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type mean_new(mean_newSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type L_omega(L_omegaSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type log_prop(log_propSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type E_obs(E_obsSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type V_obs(V_obsSEXP);
    Rcpp::traits::input_parameter< double >::type n(nSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type sigma_var(sigma_varSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXi& >::type sigma_type(sigma_typeSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type kappa_delta(kappa_deltaSEXP);
    Rcpp::traits::input_parameter< int >::type use_var(use_varSEXP);
    rcpp_result_gen = Rcpp::wrap(irmc_inner_nll_cpp(rawpreds, bi_mat, mean_new, L_omega, log_prop, E_obs, V_obs, n, sigma_var, sigma_type, kappa_delta, use_var));
    return rcpp_result_gen;
END_RCPP
}
// nll_cov_from_samples_cpp
double nll_cov_from_samples_cpp(const Eigen::MatrixXd& cp_mat, const Eigen::VectorXd& E_obs, const Eigen::MatrixXd& V_obs, double n, const Eigen::VectorXd& sigma_var, const Eigen::VectorXi& sigma_type);
RcppExport SEXP _admixr2_nll_cov_from_samples_cpp(SEXP cp_matSEXP, SEXP E_obsSEXP, SEXP V_obsSEXP, SEXP nSEXP, SEXP sigma_varSEXP, SEXP sigma_typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type cp_mat(cp_matSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type E_obs(E_obsSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type V_obs(V_obsSEXP);
    Rcpp::traits::input_parameter< double >::type n(nSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type sigma_var(sigma_varSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXi& >::type sigma_type(sigma_typeSEXP);
    rcpp_result_gen = Rcpp::wrap(nll_cov_from_samples_cpp(cp_mat, E_obs, V_obs, n, sigma_var, sigma_type));
    return rcpp_result_gen;
END_RCPP
}
// nll_var_from_samples_cpp
double nll_var_from_samples_cpp(const Eigen::MatrixXd& cp_mat, const Eigen::VectorXd& E_obs, const Eigen::VectorXd& v_obs, double n, const Eigen::VectorXd& sigma_var, const Eigen::VectorXi& sigma_type);
RcppExport SEXP _admixr2_nll_var_from_samples_cpp(SEXP cp_matSEXP, SEXP E_obsSEXP, SEXP v_obsSEXP, SEXP nSEXP, SEXP sigma_varSEXP, SEXP sigma_typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type cp_mat(cp_matSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type E_obs(E_obsSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type v_obs(v_obsSEXP);
    Rcpp::traits::input_parameter< double >::type n(nSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type sigma_var(sigma_varSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXi& >::type sigma_type(sigma_typeSEXP);
    rcpp_result_gen = Rcpp::wrap(nll_var_from_samples_cpp(cp_mat, E_obs, v_obs, n, sigma_var, sigma_type));
    return rcpp_result_gen;
END_RCPP
}
// adm_grad_partial_cpp
double adm_grad_partial_cpp(const Eigen::MatrixXd& cp_c, const Eigen::MatrixXd& dpred, const Eigen::MatrixXd& dNLL_dV, const Eigen::VectorXd& eff_dmu, double inv_nm1);
RcppExport SEXP _admixr2_adm_grad_partial_cpp(SEXP cp_cSEXP, SEXP dpredSEXP, SEXP dNLL_dVSEXP, SEXP eff_dmuSEXP, SEXP inv_nm1SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type cp_c(cp_cSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type dpred(dpredSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type dNLL_dV(dNLL_dVSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type eff_dmu(eff_dmuSEXP);
    Rcpp::traits::input_parameter< double >::type inv_nm1(inv_nm1SEXP);
    rcpp_result_gen = Rcpp::wrap(adm_grad_partial_cpp(cp_c, dpred, dNLL_dV, eff_dmu, inv_nm1));
    return rcpp_result_gen;
END_RCPP
}
// adm_grad_eta_omega_cpp
Rcpp::List adm_grad_eta_omega_cpp(const Eigen::MatrixXd& cp_c, const Eigen::MatrixXd& D_mat, const Eigen::MatrixXd& eta_mat, const Eigen::MatrixXd& z, const Eigen::MatrixXd& dNLL_dV, const Eigen::VectorXd& dNLL_dmu, const Eigen::VectorXd& sigma_mu_scale, const Eigen::VectorXi& neta1, const Eigen::VectorXi& neta2, int n_t, int n_eta);
RcppExport SEXP _admixr2_adm_grad_eta_omega_cpp(SEXP cp_cSEXP, SEXP D_matSEXP, SEXP eta_matSEXP, SEXP zSEXP, SEXP dNLL_dVSEXP, SEXP dNLL_dmuSEXP, SEXP sigma_mu_scaleSEXP, SEXP neta1SEXP, SEXP neta2SEXP, SEXP n_tSEXP, SEXP n_etaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type cp_c(cp_cSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type D_mat(D_matSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type eta_mat(eta_matSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type z(zSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type dNLL_dV(dNLL_dVSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type dNLL_dmu(dNLL_dmuSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type sigma_mu_scale(sigma_mu_scaleSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXi& >::type neta1(neta1SEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXi& >::type neta2(neta2SEXP);
    Rcpp::traits::input_parameter< int >::type n_t(n_tSEXP);
    Rcpp::traits::input_parameter< int >::type n_eta(n_etaSEXP);
    rcpp_result_gen = Rcpp::wrap(adm_grad_eta_omega_cpp(cp_c, D_mat, eta_mat, z, dNLL_dV, dNLL_dmu, sigma_mu_scale, neta1, neta2, n_t, n_eta));
    return rcpp_result_gen;
END_RCPP
}
// adm_grad_partial_var_cpp
double adm_grad_partial_var_cpp(const Eigen::MatrixXd& cp_c, const Eigen::MatrixXd& dpred, const Eigen::VectorXd& dNLL_dV_diag, const Eigen::VectorXd& eff_dmu, double inv_nm1);
RcppExport SEXP _admixr2_adm_grad_partial_var_cpp(SEXP cp_cSEXP, SEXP dpredSEXP, SEXP dNLL_dV_diagSEXP, SEXP eff_dmuSEXP, SEXP inv_nm1SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type cp_c(cp_cSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type dpred(dpredSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type dNLL_dV_diag(dNLL_dV_diagSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type eff_dmu(eff_dmuSEXP);
    Rcpp::traits::input_parameter< double >::type inv_nm1(inv_nm1SEXP);
    rcpp_result_gen = Rcpp::wrap(adm_grad_partial_var_cpp(cp_c, dpred, dNLL_dV_diag, eff_dmu, inv_nm1));
    return rcpp_result_gen;
END_RCPP
}
// adm_grad_eta_omega_var_cpp
Rcpp::List adm_grad_eta_omega_var_cpp(const Eigen::MatrixXd& cp_c, const Eigen::MatrixXd& D_mat, const Eigen::MatrixXd& eta_mat, const Eigen::MatrixXd& z, const Eigen::VectorXd& dNLL_dV_diag, const Eigen::VectorXd& dNLL_dmu, const Eigen::VectorXd& sigma_mu_scale, const Eigen::VectorXi& neta1, const Eigen::VectorXi& neta2, int n_t, int n_eta);
RcppExport SEXP _admixr2_adm_grad_eta_omega_var_cpp(SEXP cp_cSEXP, SEXP D_matSEXP, SEXP eta_matSEXP, SEXP zSEXP, SEXP dNLL_dV_diagSEXP, SEXP dNLL_dmuSEXP, SEXP sigma_mu_scaleSEXP, SEXP neta1SEXP, SEXP neta2SEXP, SEXP n_tSEXP, SEXP n_etaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type cp_c(cp_cSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type D_mat(D_matSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type eta_mat(eta_matSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type z(zSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type dNLL_dV_diag(dNLL_dV_diagSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type dNLL_dmu(dNLL_dmuSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type sigma_mu_scale(sigma_mu_scaleSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXi& >::type neta1(neta1SEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXi& >::type neta2(neta2SEXP);
    Rcpp::traits::input_parameter< int >::type n_t(n_tSEXP);
    Rcpp::traits::input_parameter< int >::type n_eta(n_etaSEXP);
    rcpp_result_gen = Rcpp::wrap(adm_grad_eta_omega_var_cpp(cp_c, D_mat, eta_mat, z, dNLL_dV_diag, dNLL_dmu, sigma_mu_scale, neta1, neta2, n_t, n_eta));
    return rcpp_result_gen;
END_RCPP
}
// irmc_grad_kernel_cpp
Rcpp::List irmc_grad_kernel_cpp(const Eigen::MatrixXd& F, const Eigen::VectorXd& w, const Eigen::VectorXd& mu, const Eigen::MatrixXd& d_mat, const Eigen::MatrixXd& invO, const Eigen::VectorXd& eff_dNLL_dmu, const Eigen::MatrixXd& dNLL_dV);
RcppExport SEXP _admixr2_irmc_grad_kernel_cpp(SEXP FSEXP, SEXP wSEXP, SEXP muSEXP, SEXP d_matSEXP, SEXP invOSEXP, SEXP eff_dNLL_dmuSEXP, SEXP dNLL_dVSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type F(FSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type w(wSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type d_mat(d_matSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type invO(invOSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type eff_dNLL_dmu(eff_dNLL_dmuSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type dNLL_dV(dNLL_dVSEXP);
    rcpp_result_gen = Rcpp::wrap(irmc_grad_kernel_cpp(F, w, mu, d_mat, invO, eff_dNLL_dmu, dNLL_dV));
    return rcpp_result_gen;
END_RCPP
}
// adm_col_sq_sum_cpp
Eigen::VectorXd adm_col_sq_sum_cpp(const Eigen::MatrixXd& m);
RcppExport SEXP _admixr2_adm_col_sq_sum_cpp(SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type m(mSEXP);
    rcpp_result_gen = Rcpp::wrap(adm_col_sq_sum_cpp(m));
    return rcpp_result_gen;
END_RCPP
}
// irmc_grad_kernel_var_cpp
Rcpp::List irmc_grad_kernel_var_cpp(const Eigen::MatrixXd& F, const Eigen::VectorXd& w, const Eigen::VectorXd& mu, const Eigen::MatrixXd& d_mat, const Eigen::MatrixXd& invO, const Eigen::VectorXd& eff_dNLL_dmu, const Eigen::VectorXd& dNLL_dV_diag);
RcppExport SEXP _admixr2_irmc_grad_kernel_var_cpp(SEXP FSEXP, SEXP wSEXP, SEXP muSEXP, SEXP d_matSEXP, SEXP invOSEXP, SEXP eff_dNLL_dmuSEXP, SEXP dNLL_dV_diagSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type F(FSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type w(wSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type d_mat(d_matSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type invO(invOSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type eff_dNLL_dmu(eff_dNLL_dmuSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type dNLL_dV_diag(dNLL_dV_diagSEXP);
    rcpp_result_gen = Rcpp::wrap(irmc_grad_kernel_var_cpp(F, w, mu, d_mat, invO, eff_dNLL_dmu, dNLL_dV_diag));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_admixr2_nll_cov_cpp", (DL_FUNC) &_admixr2_nll_cov_cpp, 5},
    {"_admixr2_nll_var_cpp", (DL_FUNC) &_admixr2_nll_var_cpp, 5},
    {"_admixr2_logdmvnorm_batch_cpp", (DL_FUNC) &_admixr2_logdmvnorm_batch_cpp, 3},
    {"_admixr2_softmax_cpp", (DL_FUNC) &_admixr2_softmax_cpp, 1},
    {"_admixr2_weighted_meancov_cpp", (DL_FUNC) &_admixr2_weighted_meancov_cpp, 2},
    {"_admixr2_compute_mean_new_cpp", (DL_FUNC) &_admixr2_compute_mean_new_cpp, 5},
    {"_admixr2_irmc_inner_nll_cpp", (DL_FUNC) &_admixr2_irmc_inner_nll_cpp, 12},
    {"_admixr2_nll_cov_from_samples_cpp", (DL_FUNC) &_admixr2_nll_cov_from_samples_cpp, 6},
    {"_admixr2_nll_var_from_samples_cpp", (DL_FUNC) &_admixr2_nll_var_from_samples_cpp, 6},
    {"_admixr2_adm_grad_partial_cpp", (DL_FUNC) &_admixr2_adm_grad_partial_cpp, 5},
    {"_admixr2_adm_grad_eta_omega_cpp", (DL_FUNC) &_admixr2_adm_grad_eta_omega_cpp, 11},
    {"_admixr2_adm_grad_partial_var_cpp", (DL_FUNC) &_admixr2_adm_grad_partial_var_cpp, 5},
    {"_admixr2_adm_grad_eta_omega_var_cpp", (DL_FUNC) &_admixr2_adm_grad_eta_omega_var_cpp, 11},
    {"_admixr2_irmc_grad_kernel_cpp", (DL_FUNC) &_admixr2_irmc_grad_kernel_cpp, 7},
    {"_admixr2_adm_col_sq_sum_cpp", (DL_FUNC) &_admixr2_adm_col_sq_sum_cpp, 1},
    {"_admixr2_irmc_grad_kernel_var_cpp", (DL_FUNC) &_admixr2_irmc_grad_kernel_var_cpp, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_admixr2(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
