# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

nll_cov_cpp <- function(E_obs, V_obs, E_pred, V_pred, n) {
    .Call(`_admixr2_nll_cov_cpp`, E_obs, V_obs, E_pred, V_pred, n)
}

nll_var_cpp <- function(E_obs, v_obs, E_pred, v_pred, n) {
    .Call(`_admixr2_nll_var_cpp`, E_obs, v_obs, E_pred, v_pred, n)
}

logdmvnorm_batch_cpp <- function(bi_mat, mean_vec, L) {
    .Call(`_admixr2_logdmvnorm_batch_cpp`, bi_mat, mean_vec, L)
}

softmax_cpp <- function(lw) {
    .Call(`_admixr2_softmax_cpp`, lw)
}

weighted_meancov_cpp <- function(F, w) {
    .Call(`_admixr2_weighted_meancov_cpp`, F, w)
}

compute_mean_new_cpp <- function(struct_paired, log_origbeta, transform_type, low, hi) {
    .Call(`_admixr2_compute_mean_new_cpp`, struct_paired, log_origbeta, transform_type, low, hi)
}

irmc_inner_nll_cpp <- function(rawpreds, bi_mat, mean_new, L_omega, log_prop, E_obs, V_obs, n, sigma_var, sigma_type, kappa_delta, use_var) {
    .Call(`_admixr2_irmc_inner_nll_cpp`, rawpreds, bi_mat, mean_new, L_omega, log_prop, E_obs, V_obs, n, sigma_var, sigma_type, kappa_delta, use_var)
}

nll_cov_from_samples_cpp <- function(cp_mat, E_obs, V_obs, n, sigma_var, sigma_type) {
    .Call(`_admixr2_nll_cov_from_samples_cpp`, cp_mat, E_obs, V_obs, n, sigma_var, sigma_type)
}

nll_var_from_samples_cpp <- function(cp_mat, E_obs, v_obs, n, sigma_var, sigma_type) {
    .Call(`_admixr2_nll_var_from_samples_cpp`, cp_mat, E_obs, v_obs, n, sigma_var, sigma_type)
}

adm_grad_partial_cpp <- function(cp_c, dpred, dNLL_dV, eff_dmu, inv_nm1) {
    .Call(`_admixr2_adm_grad_partial_cpp`, cp_c, dpred, dNLL_dV, eff_dmu, inv_nm1)
}

adm_grad_eta_omega_cpp <- function(cp_c, D_mat, eta_mat, z, dNLL_dV, dNLL_dmu, sigma_mu_scale, neta1, neta2, n_t, n_eta) {
    .Call(`_admixr2_adm_grad_eta_omega_cpp`, cp_c, D_mat, eta_mat, z, dNLL_dV, dNLL_dmu, sigma_mu_scale, neta1, neta2, n_t, n_eta)
}

adm_grad_partial_var_cpp <- function(cp_c, dpred, dNLL_dV_diag, eff_dmu, inv_nm1) {
    .Call(`_admixr2_adm_grad_partial_var_cpp`, cp_c, dpred, dNLL_dV_diag, eff_dmu, inv_nm1)
}

adm_grad_eta_omega_var_cpp <- function(cp_c, D_mat, eta_mat, z, dNLL_dV_diag, dNLL_dmu, sigma_mu_scale, neta1, neta2, n_t, n_eta) {
    .Call(`_admixr2_adm_grad_eta_omega_var_cpp`, cp_c, D_mat, eta_mat, z, dNLL_dV_diag, dNLL_dmu, sigma_mu_scale, neta1, neta2, n_t, n_eta)
}

irmc_grad_kernel_cpp <- function(F, w, mu, d_mat, invO, eff_dNLL_dmu, dNLL_dV) {
    .Call(`_admixr2_irmc_grad_kernel_cpp`, F, w, mu, d_mat, invO, eff_dNLL_dmu, dNLL_dV)
}

adm_col_sq_sum_cpp <- function(m) {
    .Call(`_admixr2_adm_col_sq_sum_cpp`, m)
}

irmc_grad_kernel_var_cpp <- function(F, w, mu, d_mat, invO, eff_dNLL_dmu, dNLL_dV_diag) {
    .Call(`_admixr2_irmc_grad_kernel_var_cpp`, F, w, mu, d_mat, invO, eff_dNLL_dmu, dNLL_dV_diag)
}

